default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: registro_gastos_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: registro_gastos_test
  username: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
